/* XPM */
static char *maticon_xpm[] = {
/* width height num_colors chars_per_pixel */
"    68    56       15            1",
/* colors */
". c #000000",
"# c #3fbea9",
"a c #4cb2a1",
"b c #59a699",
"c c #669991",
"d c #738d89",
"e c none",
"f c #826dcb",
"g c #8c62cf",
"h c #9753d3",
"i c #ad40d6",
"j c #b54dce",
"k c #b92bdd",
"l c #ba34d7",
"m c #c750bd",
/* pixels */
"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
"eeeeeeeeeeeeeeeeeee.....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
"eeeeeeeeee.eeeee...ghhhh.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
"eeeeeeee....ee..gggghhhh..eeeeeeeeeeeeeee..eeeeeeeeeeeeeeeeeeeeeeeee",
"eeeeeee.d.....ffggggghhhh..eeeeeeeeeeeee.l..eeeeeeeeeeeeeeeee.eeeeee",
"eeeeee.c...ddffffggggghhh...eeeeeeeeee..lll..eeeeeeeeeeeeee....eeeee",
"eeeee.c..ddddffffgggggghhh..eeeeeeee..lllllj..eeeeeeeeeee..mmm..eeee",
"eeee..ccdddddffffggggggghh..eeeeeee.kkllllljj.eeeeeeeeee.mmmmmm.eeee",
"eeee.cccccdddddffffgggggg...eeeee..kkkkllllll..eeeeeeee.mmmmmmm..eee",
"eee.cccccccddddff....gggg...eeee.iikkkklllll...eeeeeee.mmmmmmmmm..ee",
"eee.cccccccddddff....gggg...eeee.iikkkklllll...eeeeeee.mmmmmmmmm..ee",
"eee.bcccccccdddf.....gggg...eee.iiiikkklllll...eeeee..mmmmmmmmmm..ee",
"eee.bcccccccdd.......gggg...ee.iiiiik.kkllll...eeee.jmmmmmmmmmmm..ee",
"ee.bbbccccccc.....e.ffgg....e.hiiiii.kkkkll...eeee.jjmmmmmmmmmm...ee",
"ee.bbbbccc......eee.ffgg...e.hhiiii..kkkkll...eee.jjjmmmmmmmmm....ee",
"ee.bbbbbc......eeee.ffg.....hhhii...iikkkl....ee.jjjjmmmmmmmmm...eee",
"ee.bbbb......eeeee.ffff....ghhhh....iiikkk...ee.jjjjjjmmmmmmm...eeee",
"ee.........eeeeeee.dff....ggghh....iiiikk...e..ljjjjjjjmmmmm....eeee",
"eee.......eeeeeee.ddff...ggggh.....iiiikk....llljjjj.jjmmmm....eeeee",
"eeee...eeeeeeeeee.dddf..fggg......iiiiii....lllllj..jjjjmmm...eeeeee",
"eeeeeeeeeeeeeeee.ccdd...ffg.....e.iiiiii...kkllll..jjjjjmm...eeeeeee",
"eeeeeeeeeeeeeeee.ccdd..fff.....e.hiiiii...kkklll...jjjjjm...eeeeeeee",
"eeeeeeeeeeeeeee.cccd..ffff....e.hhiiiii...kkkll...jjjjjj....eeeeeeee",
"eeeeeeeeeeeeeee.ccc..ddff....ee.hhhiii...ikkk....lljjjj...eeeeeeeeee",
"eeeeeeeeeeeeee.cccc.dddd....ee.ghhhhii..iikk....lllljj....eeeeeeeeee",
"eeeeeeeeeeeeee.ccc..ccd....eee.ghhhhi..iiii....lllllj....eeeeeeeeeee",
"eeeeeeeeeeeee.bbcc.cccc...eee.ggghhh..iiiii...kllllll...eeeeeeeeeeee",
"eeeeeeeeeeee.bbbbccccc...eee.gggggh.hhiiii...kkkllll...eeeeeeeeeeeee",
"eeeeeeeeeeee.bbbbbccc....eee.fgggg.hhhiii....kkklll...eeeeeeeeeeeeee",
"eeeeeeeeeee.bbbbbbbc....eee.fffggghhhhii....kkkklll...eeeeeeeeeeeeee",
"eeeeeeeeee.abbbbbbb....eeee.ffffggghhhh....ikkkkkl...eeeeeeeeeeeeeee",
"eeeeeeeee.aaabbbbb.....eee.ddfffgggghh.....iikkkkk..eeeeeeeeeeeeeeee",
"eeeeeeee.###aaabbb....eee.cdddffggggg.....iiikkkk...eeeeeeeeeeeeeeee",
"eeeeeeee.###aaabbb....eee.cdddffggggg.....iiikkkk...eeeeeeeeeeeeeeee",
"eeeeeee.####aaaab....eee.cccddfffggg.....iiiiikk...eeeeeeeeeeeeeeeee",
"eeeeeee.#####aaaa....eee.cccdddfffg....e.iiiiikk...eeeeeeeeeeee..eee",
"eeeeee.######aaa....eee.ccccdddfff....e.hiiiiik....eeeeeeeeeee...eee",
"eeeeee.######aaa...eee.bcccccddff....ee.hiiiiik...eeeeeeeeeee.jl.eee",
"eeeee.########a...eeee.bbccccddd.....e.hhhiiiii...eeeeeeeeee..l.eeee",
"eeee.#########....eee.bbbbcccdd.....ee.hhhiiii...eeeeeeeeee..ll.eeee",
"eeee.########....eeee.bbbbccccd...eeee.hhhiiii...eeeeeeeee..ll.eeeee",
"eee.#########...eeee.bbbbbcccc....eee.gghhhiii...eeeeeeee.lll..eeeee",
"eee.########...eeeee.abbbbbcc....eeee.ggghhiii..eeeeeeee.lll..eeeeee",
"eee.#######...eeeee.aabbbbbc....eeeee.ggghhhi...eeeeee..ll...eeeeeee",
"eee.######....eeeee.aabbbbb....eeeeee.ggghhhi...eeee..lll...eeeeeeee",
"eee.#####....eeeeee.aaabbbb...eeeeeee.gggghhi...eee.kkll...eeeeeeeee",
"eee.#####...eeeeeee.aaaabb...eeeeeeee.gggghhhi.....kkkk...eeeeeeeeee",
"eeee.###....eeeeeee.#aaab....eeeeeeee.gggghhhiiiiiikk....eeeeeeeeeee",
"eeee..#....eeeeeeee.##aa....eeeeeeeee.ggggghhiiiiiik....eeeeeeeeeeee",
"eeeeee....eeeeeeeeee.#a...eeeeeeeeeeee.gggghhhiiiii....eeeeeeeeeeeee",
"eeeeeee..eeeeeeeeeee.#....eeeeeeeeeeee.ggggghhiiii...eeeeeeeeeeeeeee",
"eeeeeeeeeeeeeeeeeeeee....eeeeeeeeeeeee.ggggghhi.....eeeeeeeeeeeeeeee",
"eeeeeeeeeeeeeeeeeeeeee..eeeeeeeeeeeeeee..gggh.....eeeeeeeeeeeeeeeeee",
"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.........eeeeeeeeeeeeeeeeeee",
"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....eeeeeeeeeeeeeeeeeeeeee",
"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
};








